version: '3'
services:
  postgres_db:
    container_name: postgres
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - $PWD/../data/postgresql_data:/var/lib/postgresql/data
    networks:
      - net
  pg_admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    networks:
      - net
networks:
  net: